class DataConfig:

  ELEMENT_WAIT_TIME = 30
  LONG_WAIT_TIME = 120
  START_AND_STOP_APPIUM_STANDALONE = False
  CHECK_START_APPIUM = True
  LOCALHOST = "http://127.0.0.1"
  APPIUM_HOST = ""
  caps = {}
  TAUK_PROJECT_ID = "veWbY3V9R"
  TAUK_API_TOKEN = "GkdEv-vulLl5iR628rJkRR5w"